{
 "title": "Remote Write 1.1",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "recv_base",
    "label": "recv_base",
    "query": {
     "query": "label_values(prometheus_config_last_reload_successful,job)"
    }
   },
   {
    "name": "send_base",
    "label": "send_base",
    "query": {
     "query": "label_values(prometheus_config_last_reload_successful,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "prometheus_remote_storage_bytes_total",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_remote_storage_bytes_total[$__rate_interval])) by (remote_name)\n / ignoring(remote_name) group_left\n sum(rate(prometheus_remote_storage_bytes_total{remote_name=\"$recv_base\"}[$__rate_interval])) by (remote_name)\n-1\n"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_bytes_total[$__rate_interval])) by (remote_name)"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_remote_storage_bytes_total[$__rate_interval])) by (remote_name)"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=~\"receiver.*|sender.*\"}) by (job)"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total sender",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"sender-.*\"}[5m])) by (job)\n / ignoring(job) group_left\n sum(rate(process_cpu_seconds_total{job=\"$send_base\"}[5m])) by (job)\n- 1\n"
    },
    {
     "expr": "sum(increase(process_cpu_seconds_total{job=~\"sender-.*\"}[$__range])) by (job)"
    }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes sender",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"sender.*\"}) by (job)\n / ignoring(job) group_left\n sum(go_memstats_heap_sys_bytes{job=\"$send_base\"}) by (job)\n-1\n"
    },
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"sender.*\"}) by (job)"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total receiver",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"receiver-.*\"}[5m])) by (job)\n / ignoring(job) group_left\n sum(rate(process_cpu_seconds_total{job=\"$recv_base\"}[5m])) by (job)\n-1\n"
    },
    {
     "expr": "sum(increase(process_cpu_seconds_total{job=~\"receiver-.*\"}[$__range])) by (job)"
    }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes receiver",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"receiver.*\"}) by (job)\n / ignoring(job) group_left\n sum(go_memstats_heap_sys_bytes{job=\"$recv_base\"}) by (job)\n-1\n"
    },
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"receiver.*\"}) by (job)\n\n"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total sender",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"sender-.*\"}[$__rate_interval])) by (job)"
    }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes sender",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"sender.*\"}) by (job)\n"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total receiver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"receiver-.*\"}[$__rate_interval])) by (job)"
    }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes receiver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"receiver.*\"}) by (job)\n"
    }
   ]
  }
 ]
}